Brown = "MIRACLE WHIPPLE"
Columbia = "BRUNOâ€™S MANE COURSE"
Cornell = "ITHACA COW LEDGE"
Dartmouth = "WHO's AFRAID OF THE BIG GREEN SHEEP?"
Harvard = "HARVARD SHARDS"
Princeton = "MEOW NIX"
Penn = "STATE PENN"
Yale = "LITTLE BOYS BLUE"
Colgate = "DEAD RAIDERS"
"Holy Cross" = "HOLY CROSS, BATMAN!"
URI = "BRUNO HAD A LITTLE RAM"
