Brown = "Smokey the Bear"
Columbia = "Rotten to the Core Curriculum"
Cornell = "In Soviet Russia, Football Sucks at You"
Dartmouth = "It’s Drinkin’ Time!"
Harvard = "Step 1: Remove Stick From {picture of a donkey}"
Hockey = "BONESAW!"
Princeton = "Accepting Minorites since 1992"
Penn = "Quaker In Fear"
Yale = "George W. Bush Center for Kids Who Can’t Read Good"
Duquesne = "DUQUESNE SUQUES"
"Holy Cross" = "And on the 7th day, God got wasted."
URI = "In a Fight Between a Bear and an Anchor, a Bear Would Win"
