Georgetown = "Hi, Georgeous!"
Harvard = "Brown MVP {Harvard's 2024 Long Snapper}"
URI = "Big and Horney, We Ram"
Bryant = "Average Bryant Student {Boss Baby}"
Princeton = "Curiousity {Princeton's Tiger Logo with Eyes Crossed Out}"
Cornell = "Get Shucked"
Penn = "You Penn, Us Brown"
Yale = "There are two dogs inside of you {Handsome Dan and Tupper II}"
Columbia = "Dude, We're Getting The Band Back Together! {Phineas and Ferb}"
Dartmouth = "Best Dartmouth Game: Harvard vs. Yale"
